import re

def process_message(message,response_array,response):
    # splits the message abd removes all the spaces and panctuations
    list_message = re.findall(r"[\w]+|[.,!?;]",message.lower()) # using regex for filtring
    
    # Score the amout of words in the message 
    score = 0 
    for word in list_message:
        if word in response_array:
            score += 1
            
    # returns the respoese and the score of the response        
    print(score,response)
    return score,response

def get_responses(message):
    # add responses here
    response_list = [
        # add all messages you need
        process_message(message,["hi","hello","hey"], "Hey There!"),
        process_message(message,["goodbye","bye"], "Goodbye!"),
        process_message(message,["how","are",'you'], "i am doing great"),
        process_message(message,["your","name"], "my name is bot"),
        process_message(message,["help","me"], "i will do my best to assist you"),
    ]
    
    # checks all of the response scores and returns the best matching response
    response_scores =[]
    for response in response_list:
        response_scores.append(response[0]) # returns score
        
    # get the max value for the best resopjnse and store it into a var 
    winning_response = max(response_scores)
    matching_response = response_list[response_scores.index(winning_response)]
        
    # Return the best matching response and the score
    if winning_response == 0:
        bot_response = "I don't understand what you worte"
    else:
        bot_response = matching_response[1]
        
    
    print('bot response :',bot_response)
    return bot_response
    
    
# test you system
# get_responses("hi")
    
    
    # AI code generated by VS code
    # # get the responses from the file
    # with open("responses.txt","r") as file:
    #     response_array = file.read().splitlines()
        
    # # get the response with the highest score
    # response = ""
    # score = 0
    # for response in response_array:
    #     score,response = process_message(message,response_array,response)
    #     if score > score:
    #         score = score
    #         response = response
            
    # return response